stages:
    - build

build_master:
    stage: build
    image: docker
    services:
        - docker:dind
    only:
        - master
    script:
        - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
        - docker pull $CI_REGISTRY_IMAGE/dev:latest || true
        - docker build --cache-from $CI_REGISTRY_IMAGE/dev:latest -f deployment/common/Dockerfile -t $CI_REGISTRY_IMAGE/dev:latest .
        - docker push $CI_REGISTRY_IMAGE/dev:latest
        - docker build --cache-from $$CI_REGISTRY_IMAGE/dev:latest -f deployment/common/Dockerfile -t $CI_REGISTRY_IMAGE/dev:commit-$CI_COMMIT_SHA .
        - docker push $CI_REGISTRY_IMAGE/dev:commit-$CI_COMMIT_SHA

